server:
  port: 8081

spring:
  application:
    name: est-service-dev

  devtools:
    restart:
      enabled: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
